/* Self-hosts the webfonts.

   The Google Fonts stylesheet is render-blocking and costs a DNS lookup, a TLS
   handshake and a round trip before a single glyph starts downloading. Serving
   the files from our own origin removes all three, lets them be preloaded, and
   takes fonts.googleapis.com out of the privacy policy.

   Only the latin and latin-ext subsets are kept; the site is English.

   Run: node scripts/fetch-fonts.mjs   (only needed when a weight changes) */
import { mkdir, writeFile, readdir, rm } from 'node:fs/promises';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const outDir = resolve(root, 'public/fonts');

const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36';

const SPEC =
  'https://fonts.googleapis.com/css2?family=Archivo:wght@600;700&family=IBM+Plex+Sans:wght@400;500;600&family=IBM+Plex+Mono:wght@400;500&display=swap';

const KEEP = new Set(['latin', 'latin-ext']);

await mkdir(outDir, { recursive: true });
/* Clear previously generated faces only. Anything else in here (tool dotfiles)
   is left alone. */
for (const f of await readdir(outDir).catch(() => [])) {
  if (f.endsWith('.woff2')) await rm(resolve(outDir, f), { force: true });
}

const css = await (await fetch(SPEC, { headers: { 'User-Agent': UA } })).text();

/* Each block is preceded by a /* subset *\/ comment. */
const blocks = css.split('/*').slice(1);
const out = [];
let kept = 0;
let skipped = 0;

for (const raw of blocks) {
  const subset = raw.slice(0, raw.indexOf('*/')).trim();
  const body = raw.slice(raw.indexOf('*/') + 2);
  if (!KEEP.has(subset)) {
    skipped++;
    continue;
  }
  const url = body.match(/src:\s*url\((https:\/\/[^)]+)\)/)?.[1];
  const family = body.match(/font-family:\s*'([^']+)'/)?.[1];
  const weight = body.match(/font-weight:\s*(\d+)/)?.[1];
  const style = body.match(/font-style:\s*(\w+)/)?.[1] ?? 'normal';
  if (!url || !family || !weight) continue;

  const file = `${family.toLowerCase().replace(/\s+/g, '-')}-${weight}-${subset}.woff2`;
  const bin = Buffer.from(await (await fetch(url, { headers: { 'User-Agent': UA } })).arrayBuffer());
  await writeFile(resolve(outDir, file), bin);
  kept++;

  const unicode = body.match(/unicode-range:\s*([^;]+);/)?.[1]?.trim();

  out.push(
    [
      '@font-face {',
      `  font-family: '${family}';`,
      `  font-style: ${style};`,
      `  font-weight: ${weight};`,
      '  font-display: swap;',
      `  src: url('/fonts/${file}') format('woff2');`,
      unicode ? `  unicode-range: ${unicode};` : null,
      '}',
    ]
      .filter(Boolean)
      .join('\n'),
  );
}

const header = `/* Self-hosted webfonts. Generated by scripts/fetch-fonts.mjs — do not edit.
   Regenerate after changing a weight in that script's SPEC constant. */\n\n`;

await writeFile(resolve(root, 'src/styles/fonts.css'), header + out.join('\n\n') + '\n', 'utf8');

console.log(`kept ${kept} faces (latin, latin-ext), skipped ${skipped} other subsets`);
